### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==2.4.1

### ISSUE THREAD

**Issue by GiuliaGualtieri** [OpenMined/syft-heart-disease-tutorial#2]
## Description
The error message indicates that the **pip** tool is unable to find a version of the **torch** library that matches the specified version 2.4.1. The available versions listed are 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, and 2.2.2. This maybe means that torch==2.4.1 does not exist in the repository from which pip is trying to install the packages.

## How to Reproduce
1. `$ git clone https://github.com/openmined/syft-heart-disease-tutorial`
2. `cd syft-heart-disease-tutorial`
3. `conda create -n syfttutorialtest python=3.11 --yes`
4. `conda activate syfttutorialtest`
5. `pip install -r requirement`
6. See error
```shell
ERROR: Could not find a version that satisfies the requirement torch==2.4.1 (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch==2.4.1
```

## System Information
 - OS: macOS
 - OS Version: 14.5
 - Language Version: Python 3.11.10
 - Package Manager Version: Conda 24.3.0

**Comment by leriomaggio** [comment]
Hey @GiuliaGualtieri thanks very much for reporting the issue.

It is quite strange! To be fair, I haven't tried to setup the env using Conda, but looking at the `torch==2.4.1` packages [available](https://pypi.org/project/torch/2.4.1/#files) on PyPi there is a build for Python 3.11 as well.

At this point, I wonder whether "maybe" the issue is not on Python version but instead on the platform you're using? 

Perhaps your mac is not `arm64` architecture but still with Intel chip?
You could check that from command line with the following command:

```
uname -a
```

**if** that's the case, feel free to safely install an older version of PyTorch as well (e.g. `torch==2.2.2`) which is the latest supporting Intel chip on `mac_osx` architecture. 

I will update the `requirements.txt` file nonetheless to cover your case as well!

Thanks for reporting 🙌

**Comment by leriomaggio** [comment]
Should be updated and working now! 👍 

Please feel free to re-open if that's not the case!

Many thanks :)
